import type { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1b9d6c00-1111-4c2d-a2d1-000000000001",
    product_name: "Swift Personal Flex",
    bank: "Axis Bank",
    loan_type: "personal",
    rate_apr: 10.5,
    min_income: 35000,
    min_credit_score: 680,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 1.2,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Fast approval personal loan with flexible tenure and zero prepayment penalties.",
    faq: [
      {
        question: "Is there a prepayment charge?",
        answer: "No prepayment charge after the first 6 EMIs are cleared.",
      },
      {
        question: "How long does disbursal take?",
        answer: "Funds are usually disbursed within 24 hours after verification.",
      },
    ],
    terms: {
      limited_time_offer: true,
      joining_bonus: "1% processing fee waiver for applications before quarter end",
    },
  },
  {
    id: "1b9d6c00-2222-4c2d-a2d1-000000000002",
    product_name: "EduRise Student Loan",
    bank: "HDFC Bank",
    loan_type: "education",
    rate_apr: 9.25,
    min_income: 20000,
    min_credit_score: 650,
    tenure_min_months: 24,
    tenure_max_months: 84,
    processing_fee_pct: 0.75,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Education loan with long tenure options and interest-only during study period.",
    faq: [
      {
        question: "Is co-applicant mandatory?",
        answer: "A parent or guardian co-applicant is recommended for faster approval.",
      },
      {
        question: "Do I get a moratorium?",
        answer: "Yes, repayment starts 6 months after course completion.",
      },
    ],
    terms: {
      moratorium_months: 6,
    },
  },
  {
    id: "1b9d6c00-3333-4c2d-a2d1-000000000003",
    product_name: "Home Secure Advantage",
    bank: "ICICI Bank",
    loan_type: "home",
    rate_apr: 8.5,
    min_income: 60000,
    min_credit_score: 720,
    tenure_min_months: 120,
    tenure_max_months: 360,
    processing_fee_pct: 0.95,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Home loan with balanced rates, doorstep documentation pickup, and part-prepay flexibility.",
    faq: [
      {
        question: "Is part-prepayment allowed?",
        answer: "Yes, up to 20% of principal outstanding once every year without penalty.",
      },
      {
        question: "Can I balance transfer?",
        answer: "Balance transfer is supported after 12 EMIs with revised rates.",
      },
    ],
    terms: {
      doorstep_service: true,
    },
  },
  {
    id: "1b9d6c00-4444-4c2d-a2d1-000000000004",
    product_name: "AutoDrive Express",
    bank: "SBI",
    loan_type: "vehicle",
    rate_apr: 9.9,
    min_income: 30000,
    min_credit_score: 670,
    tenure_min_months: 12,
    tenure_max_months: 84,
    processing_fee_pct: 0.85,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "standard",
    summary: "Vehicle loan with fast approval for salaried applicants and low down payment options.",
    faq: [
      {
        question: "Is down payment required?",
        answer: "Minimum 10% down payment for new vehicles, 15% for used vehicles.",
      },
      {
        question: "Is pre-approval available?",
        answer: "Yes, pre-approval up to ₹12L with 30-day validity.",
      },
    ],
    terms: {
      preapproved_limit: "₹12,00,000",
    },
  },
  {
    id: "1b9d6c00-5555-4c2d-a2d1-000000000005",
    product_name: "Smart Credit Line",
    bank: "IndusInd Bank",
    loan_type: "credit_line",
    rate_apr: 12.5,
    min_income: 40000,
    min_credit_score: 690,
    tenure_min_months: 6,
    tenure_max_months: 60,
    processing_fee_pct: 1.5,
    prepayment_allowed: true,
    disbursal_speed: "instant",
    docs_level: "minimal",
    summary: "Reusable credit line with instant drawdowns and daily interest calculation.",
    faq: [
      {
        question: "How is interest charged?",
        answer: "Interest is charged only on the amount utilized, calculated daily.",
      },
      {
        question: "Is there a card?",
        answer: "You get a virtual card plus bank transfers for drawdowns.",
      },
    ],
    terms: {
      instant_drawdown: true,
    },
  },
  {
    id: "1b9d6c00-6666-4c2d-a2d1-000000000006",
    product_name: "DebtEase Consolidation",
    bank: "Kotak Mahindra",
    loan_type: "debt_consolidation",
    rate_apr: 11.4,
    min_income: 28000,
    min_credit_score: 660,
    tenure_min_months: 12,
    tenure_max_months: 72,
    processing_fee_pct: 1.35,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "low",
    summary: "One-stop consolidation loan with free closure on balance transfers after 12 months.",
    faq: [
      {
        question: "Will you close existing loans?",
        answer: "We can disburse directly to your lenders for clean closure records.",
      },
      {
        question: "Can I top up later?",
        answer: "Top-up allowed after 6 on-time EMIs and subject to credit review.",
      },
    ],
    terms: {
      balance_transfer_support: true,
    },
  },
  {
    id: "1b9d6c00-7777-4c2d-a2d1-000000000007",
    product_name: "Green Home Saver",
    bank: "Yes Bank",
    loan_type: "home",
    rate_apr: 8.9,
    min_income: 55000,
    min_credit_score: 710,
    tenure_min_months: 120,
    tenure_max_months: 300,
    processing_fee_pct: 0.9,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Home loan with energy-efficiency incentives and step-down rates for timely EMIs.",
    faq: [
      {
        question: "Any green incentive?",
        answer: "0.2% APR discount for certified green buildings.",
      },
      {
        question: "Is insurance bundled?",
        answer: "Property insurance is optional and can be bundled at discount.",
      },
    ],
    terms: {
      green_discount: "0.2% on certified buildings",
    },
  },
  {
    id: "1b9d6c00-8888-4c2d-a2d1-000000000008",
    product_name: "Startup Booster Line",
    bank: "IDFC First",
    loan_type: "credit_line",
    rate_apr: 13.2,
    min_income: 50000,
    min_credit_score: 700,
    tenure_min_months: 6,
    tenure_max_months: 48,
    processing_fee_pct: 1.75,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "minimal",
    summary: "Flexible business credit line for professionals with 48-hour onboarding and GST-based limits.",
    faq: [
      {
        question: "How is limit decided?",
        answer: "Limit is based on last 6 months of GST + bank statements.",
      },
      {
        question: "Is collateral needed?",
        answer: "No collateral required for limits up to ₹25L.",
      },
    ],
    terms: {
      gst_based_limit: true,
    },
  },
  {
    id: "1b9d6c00-9999-4c2d-a2d1-000000000009",
    product_name: "Travel Lite Personal",
    bank: "RBL Bank",
    loan_type: "personal",
    rate_apr: 12,
    min_income: 25000,
    min_credit_score: 640,
    tenure_min_months: 6,
    tenure_max_months: 48,
    processing_fee_pct: 1.1,
    prepayment_allowed: true,
    disbursal_speed: "instant",
    docs_level: "low",
    summary: "Personal loan aimed at travel with EMI holiday option for the first 2 months.",
    faq: [
      {
        question: "Do I get an EMI holiday?",
        answer: "Yes, you can start EMI after 60 days for travel planning.",
      },
      {
        question: "Is insurance bundled?",
        answer: "Trip protection add-on available at nominal cost.",
      },
    ],
    terms: {
      emi_holiday_days: 60,
    },
  },
  {
    id: "1b9d6c00-aaaa-4c2d-a2d1-000000000010",
    product_name: "NRI Home Assist",
    bank: "Federal Bank",
    loan_type: "home",
    rate_apr: 9.1,
    min_income: 70000,
    min_credit_score: 730,
    tenure_min_months: 180,
    tenure_max_months: 360,
    processing_fee_pct: 1.0,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Home loan tailored for NRIs with remote documentation and competitive spreads.",
    faq: [
      {
        question: "Can I sign remotely?",
        answer: "Yes, KYC and agreements can be executed through verified digital channels.",
      },
      {
        question: "Do you fund resale?",
        answer: "Ready and resale properties are eligible subject to valuation.",
      },
    ],
    terms: {
      remote_kyc: true,
    },
  },
];
